name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release-tarball.yml@368e641e28009262f686b74f444a2a0b8600fabd # Build-Tools main (checkout v7)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: simple-network-dashboard
